### ISSUE TITLE
Can't Change The Dark Mode & H-M-S & 24h Mode With No Touch-Bar

### ISSUE THREAD

**Issue by ywwn** [zengtianyu1215/SimpleClock#1]
**Can't Change The Dark Mode & H-M-S & 24h Mode With No Touch-Bar**
*Click the time can't work*

**Desktop:**
 - MacBook Pro (Retina, 15-inch, Mid 2015)
 - Mac OS X  Version: **[10.13.6（17G65）]**

**Additional**
*It'll cost excessive CPU(more than 70% in my activity monitor) when it run, can we make it higher efficient?*

**Comment by zengtianyu1215** [comment]
I'll fix this bug in a few days. Thanks!

**Comment by zengtianyu1215** [comment]
@YohaneTao 
Thanks for giving me a chance to make this app better! For the first problems, I'll fix them in the next version due to the current version is designed for the MBPs with Touch Bar. For the second problem, I think you should check SimpleClock.app's threads in the activity monitor instead of the whole CPU activities. I've remove some codes to simplify the app and make several tests which are not over 5% in this app. 
Thanks for making an issue!

**Comment by ywwn** [comment]
@zengtianyu1215 
Thanks for your reply. I find the second problem because my fan is too noisy when it runs. I check the activity monitor again and find the Idle Wake Ups about 5000, maybe this is reason?
Many thanks for your work.

**Comment by zengtianyu1215** [comment]
@YohaneTao 
I've released the latest version of SimpleClock in release part. The version code is v1.8.8. Please check whether your problem is solved or not. Thanks!

**Comment by ywwn** [comment]
@zengtianyu1215 
Nice! Many thanks for your work!
